[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
my_ammsol = "5DiJukQabBocT5YZ82ftKd6GKioC8FTEwqxpBshsTV7C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = 'C:\Users\Fancy\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
